import type { Metadata } from "next";
import "./globals.css";
import LayoutFooter from "./components/LayoutFooter";
import { Nunito } from "next/font/google";
import AuthProvider from "./auth/AuthProvider";

const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
  variable: "--font-nunito"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} antialiased`}
      >
        <AuthProvider>
          {children}
          <LayoutFooter />
        </AuthProvider>
      </body>
    </html>
  );
}
